name: Code lint & Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout@v5
        with:
          fetch-depth: "0"
          persist-credentials: 'false'

      - name: Run ESLint and post results
        uses: super-linter/super-linter@4d3717f7d854c0e8ed36939351503a15c5148ffc # super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS: "true"
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: "true"
          VALIDATE_GITLEAKS: "true"
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: "true"
          VALIDATE_TRIVY: "true"
          VALIDATE_YAML: "true"

  sast:
    name: "SAST Scan ${{ matrix.checks }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout@v5
        name: Checkout
        with:
          fetch-depth: "0"
          persist-credentials: 'false'
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a # actions-rust-lang/setup-rust-toolchain@v1
        # Disable caching on pull_request to avoid cache poisoning
        with:
          cache: false
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@b0aeff9875d659325e3485c0093059582a2cd40b # EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.checks }}

  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout@v5
        name: Checkout
        with:
          fetch-depth: "0"
          persist-credentials: 'false'
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a # actions-rust-lang/setup-rust-toolchain@v1
        with:
          # Disable caching on pull_request to avoid cache poisoning
          cache: false
          components: clippy, rustfmt
      - name: Run cargo check
        run: cargo check --all-targets --all-features
      - name: Run cargo fmt
        run: cargo fmt -- --check
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    needs:
      - code-checks
      - sast
      - lint
    name: Docker build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write # Required to sign SLSA provenance

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout@v5
        name: Checkout repository
        with:
          fetch-depth: "0"
          persist-credentials: 'false'

      - name: Dockerfile scan (Trivy)
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # aquasecurity/trivy-action@v0.28.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          hide-progress: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # docker/setup-buildx-action@v3

      - name: Login to the Docker registry
        id: login
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase
        name: Lowercase image name
        uses: AsZc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # AsZc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}}
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Europe/Berlin'}}
            type=sha,format=long
            type=sha,format=long,prefix={{branch}}
          images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}

      # Note: omit Actions cache for Docker layers to avoid
      #       cache-poisoning concerns flagged by Zizmor.

      - name: Build and push
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          pull: true
          context: .
          file: "Dockerfile"
          push: "true"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          provenance: true
          sbom: true

      - name: Set canonical image ref
        id: img
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}
          DIGEST: ${{ steps.build.outputs.digest }}
          REF: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}@${{ steps.build.outputs.digest }}
        run: |
          {
            printf 'image=%s\n' "$IMAGE"
            printf 'digest=%s\n' "$DIGEST"
            printf 'ref=%s\n' "$REF"
          } >> "$GITHUB_OUTPUT"

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@1aa8e0f2454b781fbf0fbf306a4c9533a0c57409 # sigstore/cosign-installer@v3.7.0

      - name: Sign multi-arch image (keyless)
        if: github.event_name != 'pull_request'
        env:
          REF: ${{ steps.img.outputs.ref }}
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes "$REF"

      # Optional: materialize an SBOM file in SPDX too (in addition to BuildKit’s)
      - name: Generate SBOM (Syft)
        if: github.event_name != 'pull_request'
        uses: anchore/sbom-action@da167eac915b4e86f08b264dbdbc867b61be6f0c # anchore/sbom-action@v0.20.5
        with:
          image: ${{ steps.img.outputs.ref }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Attach SBOM as attestation
        if: github.event_name != 'pull_request'
        env:
          REF: ${{ steps.img.outputs.ref }}
        run: |
          cosign attest --yes \
            --predicate sbom.spdx.json \
            --type spdx \
            "$REF"

      - name: Vulnerability scan (Trivy)
        if: github.event_name != 'pull_request'
        id: trivy
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: ${{ steps.img.outputs.ref }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

      - name: Upload security artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # actions/upload-artifact@v4
        with:
          name: security
          path: |
            sbom.spdx.json
